from loyalty.models import PointRule, PointRuleKind, PointRuleTrigger

DEFAULT_POINT_RULES = [
    {
        "slug": "registration",
        "title": "New Registration",
        "description": "Awarded when a new member registration is approved.",
        "rule_kind": PointRuleKind.FIXED,
        "trigger": PointRuleTrigger.ON_APPROVAL,
        "points_amount": 10,
        "icon_emoji": "🎉",
        "is_system": True,
    },
    {
        "slug": "daily_login",
        "title": "Daily Login",
        "description": "Awarded once per day when a member logs in.",
        "rule_kind": PointRuleKind.FIXED,
        "trigger": PointRuleTrigger.ON_DAILY_LOGIN,
        "points_amount": 1,
        "icon_emoji": "📅",
        "is_system": True,
    },
    {
        "slug": "referral",
        "title": "Refer a Friend",
        "description": "Awarded when a referred member is approved.",
        "rule_kind": PointRuleKind.FIXED,
        "trigger": PointRuleTrigger.ON_REFERRAL,
        "points_amount": 5,
        "icon_emoji": "🤝",
        "is_system": True,
    },
    {
        "slug": "gym_activity",
        "title": "Gym Activity",
        "description": "Manually award points for classes, check-ins, challenges, and other gym activities.",
        "rule_kind": PointRuleKind.FIXED,
        "trigger": PointRuleTrigger.MANUAL,
        "points_amount": 25,
        "icon_emoji": "🏋️",
        "is_system": True,
    },
    {
        "slug": "payment",
        "title": "Payment Reward",
        "description": "Award points based on member spend. Default: 10 TFL Points per 1000 spent.",
        "rule_kind": PointRuleKind.PAYMENT_SPEND,
        "trigger": PointRuleTrigger.MANUAL,
        "points_amount": 10,
        "spend_amount": 1000,
        "icon_emoji": "💳",
        "is_system": True,
    },
]
