# Generated by Django 5.2.15 on 2026-07-04 17:12

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_seed_site_configuration'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeClientSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.home_client_path)),
                ('image_url', models.URLField(blank=True)),
                ('row', models.PositiveSmallIntegerField(choices=[(1, 'Row 1'), (2, 'Row 2')], default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['row', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.home_gallery_path)),
                ('image_url', models.URLField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_headline', models.CharField(default='Ready to start?', max_length=200)),
                ('hero_cta_text', models.CharField(default='Enquire Now', max_length=80)),
                ('hero_image', models.ImageField(blank=True, upload_to=accounts.models.home_hero_image_path)),
                ('hero_video', models.FileField(blank=True, upload_to=accounts.models.home_hero_video_path)),
                ('hero_media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('hero_image_url', models.URLField(blank=True, help_text='Used when no hero image is uploaded.')),
                ('powerlifters_title', models.CharField(default='Powerlifters', max_length=120)),
                ('powerlifters_watermark', models.CharField(default='Iconic', max_length=80)),
                ('welcome_tagline', models.CharField(default='A Private Gym in Kathmandu', max_length=200)),
                ('welcome_paragraph_1', models.TextField(blank=True)),
                ('welcome_paragraph_2', models.TextField(blank=True)),
                ('welcome_paragraph_3', models.TextField(blank=True)),
                ('trainers_title', models.CharField(default='Meet the Trainers', max_length=120)),
                ('training_title', models.CharField(default='Training', max_length=120)),
                ('training_intro', models.TextField(blank=True)),
                ('schedule_image', models.ImageField(blank=True, upload_to=accounts.models.home_section_image_path)),
                ('schedule_image_url', models.URLField(blank=True)),
                ('rates_title', models.CharField(default='Training Session', max_length=120)),
                ('gallery_title', models.CharField(default='Training Gallery', max_length=120)),
                ('gallery_watermark', models.CharField(default='Gallery', max_length=80)),
                ('testimonials_title', models.CharField(default='What People Say About Us', max_length=160)),
                ('clients_title', models.CharField(default='Our Clients', max_length=120)),
                ('clients_intro', models.TextField(blank=True)),
                ('footer_blurb', models.TextField(blank=True)),
                ('footer_cta', models.CharField(default='Join us today!', max_length=120)),
                ('contact_address', models.TextField(blank=True, default='Kathmandu, Nepal')),
                ('contact_email', models.EmailField(blank=True, default='info@thefitlab.com.np', max_length=254)),
                ('map_embed_url', models.URLField(blank=True, default='https://maps.google.com/maps?q=Kathmandu%2C%20Nepal&z=13&output=embed')),
            ],
            options={
                'verbose_name': 'Home page settings',
                'verbose_name_plural': 'Home page settings',
            },
        ),
        migrations.CreateModel(
            name='HomePowerlifter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.home_powerlifter_path)),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomePricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(blank=True, upload_to=accounts.models.home_pricing_bg_path)),
                ('background_image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('time_info', models.CharField(max_length=200)),
                ('days_info', models.CharField(default='Sunday – Friday', max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to=accounts.models.home_trainer_path)),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HomeTrainingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='HomePricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_label', models.CharField(max_length=200)),
                ('sessions_label', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='accounts.homepricingplan')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
